name: ResNet50-first-run
save_dir: saved/
seed: 1234
target_devices: [0]

arch:
  type: ResNet50Model
  args:
    num_classes: 10

augmentation:
  type: Transforms
  args: {}

data_loader:
  type: DataLoader
  args:
    batch_size: 128
    data_dir: "data/MNIST/raw/"
    nworkers: 2
    shuffle: true
    validation_split: 0.1

loss: nll_loss

lr_scheduler:
  type: StepLR
  args:
    gamma: 0.1
    step_size: 50

metrics:
- top_1_acc
- top_3_acc

optimizer:
  type: Adam
  args:
    lr: 0.001
    weight_decay: 0

training:
  early_stop: 10
  epochs: 100
  monitor: min val_loss
  save_period: 1
  tensorboard: true
